### ISSUE TITLE
Wrong timestamps when playing traceroutes

### ISSUE THREAD

**Issue by romain-fontugne** [RIPE-NCC/tracemon#1]
When tracemon is loading, the displayed time is the UTC time specified by the user. However when playing the displayed time seems to be UTC+7.
Here is an example: http://romain.iijlab.net/test/tracemon_test.html
I request to start around 4:00 UTC, which is correct at first. But after pushing the play button the displayed time jump to 11:00UTC.

**Comment by massimocandela** [comment]
fixed, thanks

**Comment by romain-fontugne** [comment]
Thank you!
