### ISSUE TITLE
Feature request: hide old traceroutes

### ISSUE THREAD

**Issue by romain-fontugne** [RIPE-NCC/tracemon#2]
Hi, here is a small suggestion:
I would love to see old traceroutes disappearing. For example traceroutes that happened more than 30 minutes ago are not visible anymore, of course the "30 minutes" could be a parameter.

**Comment by massimocandela** [comment]
Hi Romain,
currently the traceroutes older than the interval of measurement should disappear if not "refreshed".
For example if I perform the traceroute every 15 minutes, if at some point between the same source-target pair there is a gap of time of >15min the traceroute will disappear (end eventually reappear on the next result).

Is this behaviour enough? Is it not working? Or you would like anyway a parameter that allows you to specify the validity interval?
What would be the behaviour in the following case:
- the interval of the measurement is 15, at some point the source-target pair doesn't produce new results;
- the interval specified by you is 20.
Should I leave the traceroute anyway for 20 or for 15 minutes?

**Comment by romain-fontugne** [comment]
Ah I see. Thanks Massimo, I haven't realized that this was already in place.

I wish we could reduce this timeout. For example, for the results at the bottom of this page: http://ihr.iijlab.net/ihr/6848/asn/?date=2018-03-13&last=7&discodate=2018-03-13+02%3A03%3A59&discoid=131915248

We detected an outage that lasted 20 minutes and involving four probes. We show that with a built-in measurement (traceroute every 30 minutes). But 2 probes (14647 and 13630) have traceroutes 5 minutes before the outage. So during the outage it looks like these 2 probes are not impacted by the outage, whereas the 2 others clearly cannot reach the target. If I could reduce the timeout, to let's say 15 minutes then I would see 2 probes cannot reach the target and no information for the 2 probes that have no traceroute during the outage. 

Maybe my usage of tracemon is very specific, and it is ok if you don't want to modify the code for this corner case, but I think it could also help readability when there is a lot of probes/destinations.

To answer your last question, I think the timeout value should always be smaller or equal to the measurement period. So if someone specify 20min for a 15min-interval measurement, it should fall back to 15.

**Comment by massimocandela** [comment]
Thanks for the feedback. I really appreciate you using my tools in your project. I just committed your feature request (available here on git). If you are using directly the code, just do a git pull. If you are embedding the widget from Atlas (preferred), you will automatically have the latest version with the next public release (soon). 

In the embedding code you can now specify: maximumTracerouteValiditySeconds: AMOUNT

**Comment by romain-fontugne** [comment]
Thanks, that's awesome! I love that tool :)
